"""
Shared utilities for metrics file management.
Handles safe concurrent read/write with file locking.
"""

import fcntl
import os
from pathlib import Path
from typing import Dict

METRICS_FILE = Path(__file__).parent / 'metrics.prom'


def write_metrics_file(new_metrics: Dict[str, str]):
    """
    Update metrics file with new values.
    Uses file locking to ensure thread-safe writes.
    
    Args:
        new_metrics: Dict mapping metric keys to full metric lines
    """
    METRICS_FILE.touch(exist_ok=True)
    
    with open(METRICS_FILE, 'r+') as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        
        try:
            f.seek(0)
            existing = {}
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split()
                    if len(parts) >= 2:
                        metric_key = parts[0]
                        existing[metric_key] = line
            
            existing.update(new_metrics)
            
            f.seek(0)
            f.truncate()
            
            f.write("# Prometheus metrics for recommendation service\n")
            f.write(f"# Generated by monitoring scripts\n\n")
            
            for metric_line in sorted(existing.values()):
                f.write(metric_line + '\n')
            
            f.flush()
            os.fsync(f.fileno())
            
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def format_gauge(name: str, value: float, labels: Dict[str, str] = None) -> Dict[str, str]:
    """Format a gauge metric."""
    if labels:
        label_str = ','.join([f'{k}="{v}"' for k, v in labels.items()])
        metric_key = f"{name}{{{label_str}}}"
    else:
        metric_key = name
    
    metric_line = f"{metric_key} {value}"
    return {metric_key: metric_line}